#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

eval "$(fasd --init auto)"

export PS1='${vcs_info_msg_0_}> '
setopt promptsubst
#●

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#export PS1="> "
autoload -Uz promptinit
promptinit
#prompt bart
#prompt steeef

autoload -U zmv
alias mmv='noglob zmv -W'
#alias t='todo-txt'
alias se='sudoedit'

# Git aliases
alias gmv='git mv'
alias grm='git rm'

# automatically show directory listing after cd
function chpwd() {
    emulate -L zsh
    ls
}

zstyle ':completion:*' menu select
zmodload zsh/complist
# Use hjkl keys for autocomplete menus
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

PATH="$HOME/bin:$HOME/.local/bin:$PATH"

# Color files differently in ls
eval $( dircolors -b $HOME/.dircolors )

source $HOME/.zsh/calc.plugin.zsh

source $HOME/.antigen/antigen.zsh

antigen bundle willghatch/zsh-saneopt
antigen bundle veelenga/crystal-zsh
TIPZ_TEXT='Next time try: '
antigen bundle molovo/tipz 
antigen bundle hlissner/zsh-autopair
antigen bundle psprint/history-search-multi-word
antigen bundle supercrabtree/k
antigen bundle zdharma/fast-syntax-highlighting
#antigen bundle teancom/k

antigen apply
