#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

eval "$(fasd --init auto)"

export PS1="> "

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#export PS1="> "
autoload -Uz promptinit
promptinit
#prompt bart
#prompt steeef

autoload -U zmv
alias mmv='noglob zmv -W'
#alias t='todo-txt'

function chpwd() {
    emulate -L zsh
    ls
}

PATH="$HOME/bin:$HOME/.local/bin:$PATH"
